# -*- coding: utf-8 -*-
"""BCCDAy4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113LxUyN1Ipwo-Yyx2VhcivzbXlcFX-ak
"""

list=[1,2,3,4,5]
list.append(10) # to add a element
print(list)

list.insert (1,20)
print(list)

list.sort()
print(list)

list=[1,2,3,4,5,20]
print(list)
list.remove(4)
print(list)

#POP Function
num=[5,10,15,20]
x=num.pop(2)
print(num,x)

list=[1,2,2,2,3,4,5]
list.reverse()
print(list)
print(list.count(2))
list2=["a","b","c","d"]
print("index of c = ",list2.index("c"))

a=[1,2]
b=[3,4]
a.extend(b)
print(a)
#clear() fucntion
list=[1,2,3,4,5,]
list.clear()
print(list)

# Remove Duplicates from list
number = [5,7,7,9,3,3,5,3,2,2,4]
rem=[]
for i in number:
  if i not in rem:
    rem.append(i)
print("Actual list:",number)
print("after removing:",rem)

# Find second largest element
num=[45,67,12,89,78]
maximum=second_largest=float('-inf')
for i in num:
  if i>maximum:
    second_largest=maximum
    maximum=i
  elif i>second_largest and i!=maximum:
    second_largest=i
print("second largest value = ",second_largest)

# Find All Pairs whose sum is equal
num=[2,4,3,6,8,7,9]
target=10
rem=[]
for i in range(len(num)):
  for j in range(i+1,len(num)):
    if (num[i]+num[j]==target):
      rem.append((num[i],num[j]))
print("pair is =",rem)

# find Frequeecy Of each elemet
# counthow many times each elemt
num=[1,1,1,1,2,2,2,3,3,4,4,5,5]
dict={}
for i in num:
  if i in dict:
    dict[i]+=1
  else:
    dict[i]=1

