# -*- coding: utf-8 -*-
"""BCC training day 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwKCioq3mAbzFTsvnLcbgqeWZSc-bgnM
"""

# print 1 to 20 number
for i in range (1,21):
  print (i)
  #print even odd number from 1 to 30
  if i % 2 == 0:
    print ("The Number is Even")
  else:
      print ("The Number is Odd")

for i in range (1,21):
  if i%2==0:
    print(i,"even")

print ("odd number")
for i in range (1,21):
  if i



# print sum of all natural numbers
num = 10
add=0
for i in range (1,num+1):
  add=add+i
print ("Addition=",add)

# Find factorial of a number

n = int(input("Enter a number: "))

fact = 1

for i in range(1, n+1):
    fact = fact * i

print("Factorial =", fact)

# Find factorial of a number

n = int(input("Enter a number: "))

fact = 1

for i in range(1, n+1):
    fact = fact * i

print("Factorial =", fact)

def factorial (x):
  if x==0:
    return 1
  return x*factorial (x-1)

print (factorial(5))

# perform the mutiplication table
num=int(input("enter any number:"))
for i in range (1,11):
  print(num,"x",i,"=",num*1)

# perform the mutiplication table
num=int(input("enter any number:"))
for i in range (1,11):
  print(num,"x",i,"=",num*1)

#count
number=int(input("enter any number:"))
count=0
while number>0:
  count+=1
  number //=10
  print(count)

# reverse number 12345 ==> 54321
num = int(input("Enter a number: "))
rev = 0
while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num = num // 10
print("Reversed number =", rev)

number=12345
reverse=0
while number>0:
  remainder=number%10
  reverse=(reverse*10)+remainder
  number=number//10
print(reverse)

