# -*- coding: utf-8 -*-
"""bcc-1 sam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14muqRnS4c6FxC7VlzgYRMT9Qb4dXWsJ9
"""

name="Jai"
age="20"
department="mech"
salary=10000000
cgpa=7.6


print("name",name)
print("age",age)
print("department",department)
print("salary",salary)
print("cgpa",cgpa)

name="swanandi mahajan"
age="20"
department="mech"
salary=10000000
cgpa=7.6


print(type(name))
print(type(age))
print(type(department))
print(type(salary))
print(type(cgpa))

num1=10
num2=20
num3=num1+num2
print(num3)

#find area of rectangle
l=20
b=2
area=l*b
print(area)

#swap two num
a=12
b=32
print("a:",b)
print("b:",a)

#find sqr and cube of a num
a=int(input("enter the value of a:"))
sqr=a*a
cube=a*a*a
print("enter the square",a*a)
print("enter the cube ",a*a*a )

#convert minits to hr
a=int(input("enter the minits:"))
print("time in hour",a/60)

#convert km to m
a=int(input("enter the value in km"))
print("value converted in m",a*1000)

#find your current age
a=int(input("enter the year of birth"))
b=int(input("enter the current year"))
print("your current age",b-a)

#convert rupees to dollar
a=int(input("enter the value in rupees"))
print("amount in dollar",a/92)

#calculate total marks and percentage cgpa
a=int(input("enter the marks of sub 1"))
b=int(input("enter the marks of sub 2"))
c=int(input("enter the marks of sub 3"))
d=int(input("enter the marks of sub 4"))
e=int(input("enter the marks of sub 5"))
total=a+b+c+d+e
print("total marks",total)
print("percentage",total/500)*500
print("cgpa is:",cgpa)